name: Telegram Notification

on:
  push:
    branches:
      - '*'
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  send-telegram-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        uses: Telegram-Markdown-Bot/telegram-send-message@v2
        with:
          bot_token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            New commit in PR #${{ github.event.number }}:
            ${{ github.event.head_commit.message }}
            Author: ${{ github.event.head_commit.author.name }}
            SHA: ${{ github.sha }}
