# This is a basic workflow that is manually triggered
name: Pull Request javascript-dev

# Controls when the action will run. Workflow runs when manually triggered using the UI or API.
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_commentary:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Webhook
      uses: distributhor/workflow-webhook@v3.0.7
      with:
        webhook_url: "https://hook.eu2.make.com/c98145z4s5jbpw906x26s15zobhpko07"
        data: '{ "repository": "Hello world" }'
