name: Telegram Notification

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - 'main'

jobs:
  send-telegram-notification:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        uses: appleboy/telegram-action@v0.3.0
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Новый коммит в Pull Request #${{ github.event.number }}:
            ${{ github.event.head_commit.message }}
            Автор: ${{ github.event.head_commit.author.name }}
            SHA: ${{ github.sha }}
